### ISSUE TITLE
./app folder from the v5.13.7 update

### ISSUE THREAD

**Issue by 10scar** [Lukas1h/react-native-kindle#1]
hello do you have the ./app folder of the v5.13.7 update? 
to do some tests on the 12.12.2.2.2, it is difficult to get this resource without having a kindle with this version.

**Comment by Lukas1h** [comment]
Yeah, it's pretty easy to extract from Amazon updates using `kindletool`. I'll have some more information on how to get it tomorrow morning.

**Comment by Lukas1h** [comment]
See [this post](https://www.mobileread.com/forums/showpost.php?p=4255948&postcount=2) on mobileread.com.

In the `kindleUpdate` folder there should be the `app` folder you need.
